schema: ./graphql/schema.graphql
documents: '**/*.graphql'
extensions:
  endpoints:
    "AWS":
      url: https://2iokr4xwcbh5tfquhqvmos5wu4.appsync-api.eu-central-1.amazonaws.com/graphql
      headers:
        "x-api-key": "da2-vldwms3qwnbyrcbrsfgxqoewqq"
      introspect: true


include:
  - _aws.graphql